language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: travis_wait 60 bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.06
os:
  - linux
